services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
  auction-svc:
    image: jpcassidy/carauction-auction-svc:latest
    container_name: auction-svc
    build:
      context: .
      dockerfile: backend/src/Auction/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=7001
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: jpcassidy/carauction-search-svc:latest
    container_name: search-svc
    build:
      context: .
      dockerfile: backend/src/Search/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=7002
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
  identity-svc:
    image: jpcassidy/carauction-identity-svc:latest
    container_name: identity-svc
    build:
      context: .
      dockerfile: backend/src/Infrastructure/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=5000
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway-svc:
    image: jpcassidy/carauction-gateway-svc:latest
    container_name: gateway-svc
    build:
      context: .
      dockerfile: backend/src/ApiGateways/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=6001
    ports:
      - 6001:80
  bid-svc:
    image: jpcassidy/carauction-bid-svc:latest
    container_name: bid-svc
    build:
      context: .
      dockerfile: backend/src/Bidding/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=7003
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 7003:80
    depends_on:
      - mongodb
      - rabbitmq
volumes:
  postgres_data:
  mongo_data:
